# 1. Paso: Cargar dos conjuntos de datos, train.csv y test.csv. mostrar las primeras filas de cada uno.

In [2]:
import pandas as pd

# Cargar el archivo CSV
data = pd.read_csv('train.csv')
data2 = pd.read_csv('test.csv')

# Mostrar las primeras filas del dataset
data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [3]:
data2.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

# 2. Definir listas de columnas para conservar (categÃ³ricas y numÃ©ricas) y para eliminar.

In [4]:
# Listas de caracterÃ­sticas a mantener y eliminar
columns_to_drop = [
    "Street", "Alley", "LotShape", "LandContour", "Utilities", "LandSlope",
    "Exterior2nd", "ExterCond", "Foundation", "BsmtCond", "Electrical",
    "Functional", "GarageType", "GarageFinish", "GarageQual", "PavedDrive",
    "Fence", "MiscFeature", "SaleType"
]

columns_to_keep_categorical = [
    "MSZoning", "LotConfig", "Neighborhood", "Condition1", "Condition2",
    "BldgType", "HouseStyle", "RoofStyle", "RoofMatl", "Exterior1st",
    "MasVnrType", "ExterQual", "BsmtQual", "BsmtExposure", "BsmtFinType1",
    "Heating", "HeatingQC", "CentralAir", "KitchenQual", "FireplaceQu",
    "GarageCond", "PoolQC", "SaleCondition"
]

columns_to_keep_numeric = [
    "OverallQual", "YearBuilt", "YearRemodAdd", "MasVnrArea", "BsmtFinSF1",
    "TotalBsmtSF", "1stFlrSF", "GrLivArea", "FullBath", "HalfBath",
    "TotRmsAbvGrd", "Fireplaces", "GarageYrBlt", "GarageCars", "GarageArea",
    "WoodDeckSF", "OpenPorchSF"
]

# Conservar solo las columnas que decidimos mantener y eliminar las no deseadas
data_cleaned = data.drop(columns=columns_to_drop)
data2_cleaned = data2.drop(columns=columns_to_drop)

# Dejamos solo las columnas que queremos mantener
data_cleaned = data_cleaned[["Id"] + columns_to_keep_categorical + columns_to_keep_numeric + ["SalePrice"]]
data2_cleaned = data2_cleaned[["Id"] + columns_to_keep_categorical + columns_to_keep_numeric]

data_cleaned.head()

,Id,MSZoning,LotConfig,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,RoofStyle,RoofMatl,...,FullBath,HalfBath,TotRmsAbvGrd,Fireplaces,GarageYrBlt,GarageCars,GarageArea,WoodDeckSF,OpenPorchSF,SalePrice
0,1,RL,Inside,CollgCr,Norm,Norm,1Fam,2Story,Gable,CompShg,...,2,1,8,0,2003.0,2,548,0,61,208500
1,2,RL,FR2,Veenker,Feedr,Norm,1Fam,1Story,Gable,CompShg,...,2,0,6,1,1976.0,2,460,298,0,181500
2,3,RL,Inside,CollgCr,Norm,Norm,1Fam,2Story,Gable,CompShg,...,2,1,6,1,2001.0,2,608,0,42,223500
3,4,RL,Corner,Crawfor,Norm,Norm,1Fam,2Story,Gable,CompShg,...,1,0,7,1,1998.0,3,642,0,35,140000
4,5,RL,FR2,NoRidge,Norm,Norm,1Fam,2Story,Gable,CompShg,...,2,1,9,1,2000.0,3,836,192,84,250000

# 3. Analizar los valores faltantes.

In [5]:
# Determinar la cantidad de valores faltantes por caracterÃ­stica
missing_values = data_cleaned.isnull().sum()
missing_values2 = data2_cleaned.isnull().sum()

# Filtrar solo las caracterÃ­sticas que tienen valores faltantes
missing_values = missing_values[missing_values > 0]
missing_values2 = missing_values2[missing_values2 > 0]

missing_values

MasVnrType       872
BsmtQual          37
BsmtExposure      38
BsmtFinType1      37
FireplaceQu      690
GarageCond        81
PoolQC          1453
MasVnrArea         8
GarageYrBlt       81
dtype: int64

# 4. Identificar y manejar valores faltantes imputÃ¡ndolos usando la moda para caracterÃ­sticas categÃ³ricas y la mediana para caracterÃ­sticas numÃ©ricas.

In [6]:
# Imputar valores faltantes en caracterÃ­sticas categÃ³ricas con la moda
for column in missing_values.index:
    if column in columns_to_keep_categorical:
        mode_value = data_cleaned[column].mode()[0]
        data_cleaned[column].fillna(mode_value, inplace=True)

# Imputar valores faltantes en caracterÃ­sticas numÃ©ricas con la mediana
for column in missing_values.index:
    if column in columns_to_keep_numeric:
        median_value = data_cleaned[column].median()
        data_cleaned[column].fillna(median_value, inplace=True)
        
        

# Imputar valores faltantes en caracterÃ­sticas categÃ³ricas con la moda
for column in missing_values2.index:
    if column in columns_to_keep_categorical:
        mode_value = data2_cleaned[column].mode()[0]
        data2_cleaned[column].fillna(mode_value, inplace=True)

# Imputar valores faltantes en caracterÃ­sticas numÃ©ricas con la mediana
for column in missing_values2.index:
    if column in columns_to_keep_numeric:
        median_value = data2_cleaned[column].median()
        data2_cleaned[column].fillna(median_value, inplace=True)

# Verificar si aÃºn hay valores faltantes
data_cleaned.isnull().sum().max()
data2_cleaned.isnull().sum().max()

0

### One-hot encoding: Aplicaste codificaciÃ³n one-hot a las caracterÃ­sticas categÃ³ricas en tus conjuntos de datos. Utilizaste la funciÃ³n pd.get_dummies para hacerlo.

In [7]:
# Realizar one-hot encoding de las caracterÃ­sticas categÃ³ricas
data_encoded = pd.get_dummies(data_cleaned, columns=columns_to_keep_categorical)

data2_encoded = pd.get_dummies(data_cleaned, columns=columns_to_keep_categorical)

data_encoded.head()

,Id,OverallQual,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,TotalBsmtSF,1stFlrSF,GrLivArea,FullBath,...,GarageCond_TA,PoolQC_Ex,PoolQC_Fa,PoolQC_Gd,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,1,7,2003,2003,196.0,706,856,856,1710,2,...,True,False,False,True,False,False,False,False,True,False
1,2,6,1976,1976,0.0,978,1262,1262,1262,2,...,True,False,False,True,False,False,False,False,True,False
2,3,7,2001,2002,162.0,486,920,920,1786,2,...,True,False,False,True,False,False,False,False,True,False
3,4,7,1915,1970,0.0,216,756,961,1717,1,...,True,False,False,True,True,False,False,False,False,False
4,5,8,2000,2000,350.0,655,1145,1145,2198,2,...,True,False,False,True,False,False,False,False,True,False

### DivisiÃ³n de datos y entrenamiento de RandomForest: 
### Divide los datos en conjuntos de entrenamiento y validaciÃ³n, y luego entrenaste un modelo de Random Forest. TambiÃ©n calculaste el error cuadrÃ¡tico medio (MSE) para las predicciones de este modelo.

In [21]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

# Definir las caracterÃ­sticas (X) y la variable objetivo (y)
X = data_encoded.drop(columns=["Id", "SalePrice"])
y = data_encoded["SalePrice"]

X2 = data2_encoded.drop(columns=["Id", "SalePrice"])
y2 = data2_encoded["SalePrice"]

# Dividir los datos en conjuntos de entrenamiento y validaciÃ³n
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

X_test, X2_val, y_test, y2_val = train_test_split(X2, y2, test_size=0.2, random_state=42)

# # Entrenar el modelo Random Forest
# rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
# rf_model.fit(X_train, y_train)

# rf_model.fit(X_test, y_test)

# # Predecir en el conjunto de validaciÃ³n
# rf_predictions = rf_model.predict(X_val)

# # Calcular el error cuadrÃ¡tico medio (MSE) para las predicciones
# rf_mse = mean_squared_error(y_val, rf_predictions)

# rf_mse

### Entrenamiento y evaluaciÃ³n de XGBoost: Entrenaste un modelo de regresiÃ³n XGBoost y calculaste el MSE para sus predicciones.

In [23]:
import xgboost as xgb

# Entrenar el modelo XGBoost Regression
xgb_model = xgb.XGBRegressor(objective ='reg:squarederror', n_estimators=100, seed=42)
xgb_model.fit(X_train, y_train)

# Predecir en el conjunto de validaciÃ³n
xgb_predictions = xgb_model.predict(X_val)

# Calcular el error cuadrÃ¡tico medio (MSE) para las predicciones
xgb_mse = mean_squared_error(y_val, xgb_predictions)

xgb_mse

c:\Users\reyco\anaconda3\lib\site-packages\xgboost\data.py:312: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(dtype):
c:\Users\reyco\anaconda3\lib\site-packages\xgboost\data.py:314: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  elif is_categorical_dtype(dtype) and enable_categorical:
c:\Users\reyco\anaconda3\lib\site-packages\xgboost\data.py:345: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if is_categorical_dtype(dtype)
c:\Users\reyco\anaconda3\lib\site-packages\xgboost\data.py:336: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  return is_int or is_bool or is_float or is_categorical_dtype(dtype)
c:\Users\reyco\anaconda3\lib\site-packages\xgboost\data.py:440: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(data):
c:\Users\reyco\anaconda3\lib\site-packages\xgboost\data.py:312: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(dtype):
c:\Users\reyco\anaconda3\lib\site-packages\xgboost\data.py:314: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  elif is_categorical_dtype(dtype) and enable_categorical:
c:\Users\reyco\anaconda3\lib\site-packages\xgboost\data.py:345: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if is_categorical_dtype(dtype)
c:\Users\reyco\anaconda3\lib\site-packages\xgboost\data.py:336: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  return is_int or is_bool or is_float or is_categorical_dtype(dtype)

1031590012.2509824

### BÃºsqueda de hiperparÃ¡metros: Utilizaste RandomizedSearchCV para buscar la mejor combinaciÃ³n de hiperparÃ¡metros para el modelo XGBoost.

In [24]:
from sklearn.model_selection import RandomizedSearchCV
import numpy as np

# ParÃ¡metros a considerar en el ajuste
param_distributions = {
    'n_estimators': np.arange(100, 1001, 100),
    'learning_rate': [0.001, 0.01, 0.1, 0.2, 0.3],
    'max_depth': np.arange(3, 11, 1),
    'min_child_weight': np.arange(1, 11, 1),
    'gamma': [i/10.0 for i in range(0, 5)],
    'subsample': [i/10.0 for i in range(6, 11)],
    'colsample_bytree': [i/10.0 for i in range(6, 11)],
    'reg_alpha': [0, 0.001, 0.005, 0.01, 0.05]
}

# Utiliza RandomizedSearchCV para encontrar la mejor combinaciÃ³n de parÃ¡metros
random_search = RandomizedSearchCV(xgb_model, param_distributions=param_distributions,
                                   n_iter=50, scoring='neg_mean_squared_error',
                                   cv=3, verbose=2, random_state=42, n_jobs=-1)

random_search.fit(X_train, y_train)

# Actualiza el modelo xgb_model con los mejores parÃ¡metros encontrados
xgb_model = random_search.best_estimator_

Fitting 3 folds for each of 50 candidates, totalling 150 fits

c:\Users\reyco\anaconda3\lib\site-packages\xgboost\data.py:312: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(dtype):
c:\Users\reyco\anaconda3\lib\site-packages\xgboost\data.py:314: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  elif is_categorical_dtype(dtype) and enable_categorical:
c:\Users\reyco\anaconda3\lib\site-packages\xgboost\data.py:345: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if is_categorical_dtype(dtype)
c:\Users\reyco\anaconda3\lib\site-packages\xgboost\data.py:336: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  return is_int or is_bool or is_float or is_categorical_dtype(dtype)
c:\Users\reyco\anaconda3\lib\site-packages\xgboost\data.py:440: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(data):

### EvaluaciÃ³n adicional de XGBoost: Calculaste el error absoluto medio (MAE) y el error cuadrÃ¡tico medio raÃ­z (RMSE) para las predicciones del modelo XGBoost.

In [11]:
from sklearn.metrics import mean_absolute_error

# Calcular el error absoluto medio (MAE)
xgb_mae = mean_absolute_error(y_val, xgb_predictions)

# Calcular el error cuadrÃ¡tico medio raÃ­z (RMSE)
xgb_rmse = mean_squared_error(y_val, xgb_predictions, squared=False)

xgb_mae, xgb_rmse

(18188.623301048803, 32118.374993934274)

### Importancia de las caracterÃ­sticas: Se extrajo la importancia de las caracterÃ­sticas del modelo XGBoost y se visualizÃ³.

In [12]:
# Obtener la importancia de las caracterÃ­sticas
feature_importances = xgb_model.feature_importances_

# Crear un DataFrame para visualizar la importancia de las caracterÃ­sticas
features_df = pd.DataFrame({
    'Feature': X.columns,
    'Importance': feature_importances
})

# Ordenar las caracterÃ­sticas por importancia
features_df = features_df.sort_values(by='Importance', ascending=False)

# Mostrar las 10 caracterÃ­sticas mÃ¡s importantes
top_features = features_df.head(10)
top_features

            Feature  Importance
117    ExterQual_TA    0.231228
0       OverallQual    0.149907
115    ExterQual_Fa    0.079535
13       GarageCars    0.075689
118     BsmtQual_Ex    0.047144
8          FullBath    0.022219
7         GrLivArea    0.022161
145  KitchenQual_Ex    0.021338
116    ExterQual_Gd    0.017847
114    ExterQual_Ex    0.012318

### Preprocesamiento del conjunto de datos de prueba:
- Cargaste el archivo test.csv.
- Eliminaste las caracterÃ­sticas no deseadas y preparaste los datos de forma similar a como lo hiciste con el conjunto de entrenamiento.
- Aplicaste codificaciÃ³n one-hot al conjunto de datos de prueba.
- Identificaste las columnas que podrÃ­an faltar en el conjunto de prueba despuÃ©s de la codificaciÃ³n one-hot y las agregaste.
- Verificaste el preprocesamiento.

In [20]:
# Cargar el archivo test.csv
test_data = pd.read_csv('test.csv')

# Eliminar las caracterÃ­sticas no deseadas y preparar los datos como lo hicimos anteriormente
test_data_cleaned = test_data.drop(columns=columns_to_drop)
test_data_cleaned = test_data_cleaned[["Id"] + columns_to_keep_categorical + columns_to_keep_numeric]

# 1. Identificar las columnas que podrÃ­an faltar en el conjunto de prueba despuÃ©s de la codificaciÃ³n one-hot:
missing_cols = set(data_encoded.columns) - set(test_data_encoded.columns)

# 2. Aplicar la codificaciÃ³n one-hot al conjunto de datos de prueba:
test_data_encoded = pd.get_dummies(test_data_cleaned, columns=columns_to_keep_categorical)

# 3. AÃ±adir las columnas faltantes al conjunto de prueba y asegurarse de que las columnas estÃ©n en el mismo orden que en el conjunto de entrenamiento:
for c in missing_cols:
    test_data_encoded[c] = 0
test_data_encoded = test_data_encoded[data_encoded.columns]

# Verificar el preprocesamiento
test_data_encoded.head()


# Imputar valores faltantes
for column in columns_to_keep_categorical + columns_to_keep_numeric:
    if column in columns_to_keep_categorical:
        mode_value = data_cleaned[column].mode()[0]
        test_data_cleaned[column].fillna(mode_value, inplace=True)
    if column in columns_to_keep_numeric:
        median_value = data_cleaned[column].median()
        test_data_cleaned[column].fillna(median_value, inplace=True)

# Codificar caracterÃ­sticas categÃ³ricas
test_data_encoded = pd.get_dummies(test_data_cleaned, columns=columns_to_keep_categorical)

# Asegurar que el conjunto de datos de prueba tenga las mismas caracterÃ­sticas que el conjunto de entrenamiento
for c in missing_cols:
    test_data_encoded[c] = 0
test_data_encoded = test_data_encoded[X.columns]

# Verificar si el preprocesamiento fue exitoso
test_data_encoded.head()

,OverallQual,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,TotalBsmtSF,1stFlrSF,GrLivArea,FullBath,HalfBath,...,GarageCond_TA,PoolQC_Ex,PoolQC_Fa,PoolQC_Gd,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,5,1961,1961,0.0,468.0,882.0,896,896,1,0,...,True,False,0,True,False,False,False,False,True,False
1,6,1958,1958,108.0,923.0,1329.0,1329,1329,1,1,...,True,False,0,True,False,False,False,False,True,False
2,5,1997,1998,0.0,791.0,928.0,928,1629,2,1,...,True,False,0,True,False,False,False,False,True,False
3,6,1998,1998,20.0,602.0,926.0,926,1604,2,1,...,True,False,0,True,False,False,False,False,True,False
4,8,1992,1992,0.0,263.0,1280.0,1280,1280,2,0,...,True,False,0,True,False,False,False,False,True,False

### EvaluaciÃ³n del modelo: Calculaste el R^2 en los conjuntos de entrenamiento y prueba.

In [14]:
train_score = xgb_model.score(X_train, y_train)
print(f"Train Score (R^2): {train_score}")

test_score = xgb_model.score(X_test, y_test)
print(f"Test Score (R^2): {test_score}")

Train Score (R^2): 0.9611636996070122
Test Score (R^2): 0.9611636996070122

c:\Users\reyco\anaconda3\lib\site-packages\xgboost\data.py:312: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(dtype):
c:\Users\reyco\anaconda3\lib\site-packages\xgboost\data.py:314: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  elif is_categorical_dtype(dtype) and enable_categorical:
c:\Users\reyco\anaconda3\lib\site-packages\xgboost\data.py:345: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if is_categorical_dtype(dtype)
c:\Users\reyco\anaconda3\lib\site-packages\xgboost\data.py:336: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  return is_int or is_bool or is_float or is_categorical_dtype(dtype)
c:\Users\reyco\anaconda3\lib\site-packages\xgboost\data.py:312: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(dtype):
c:\Users\reyco\anaconda3\lib\site-packages\xgboost\data.py:314: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  elif is_categorical_dtype(dtype) and enable_categorical:
c:\Users\reyco\anaconda3\lib\site-packages\xgboost\data.py:345: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if is_categorical_dtype(dtype)
c:\Users\reyco\anaconda3\lib\site-packages\xgboost\data.py:336: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  return is_int or is_bool or is_float or is_categorical_dtype(dtype)

### Predicciones del modelo: Realizaste predicciones con el modelo XGBoost en el conjunto de datos de prueba y comparaste las predicciones con los valores reales.

In [15]:
# Realizar predicciones con el modelo Random Forest en el conjunto de datos de prueba
sample_submission = pd.read_csv('sample_submission.csv')



test_predictions_rf = xgb_model.predict(test_data_encoded)

# Comparar las predicciones con los valores reales
comparison_df = pd.DataFrame({
    'Id': test_data["Id"],
    'Real SalePrice': sample_submission["SalePrice"],
    'Predicted SalePrice': test_predictions_rf
})

comparison_df

c:\Users\reyco\anaconda3\lib\site-packages\xgboost\data.py:312: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(dtype):
c:\Users\reyco\anaconda3\lib\site-packages\xgboost\data.py:314: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  elif is_categorical_dtype(dtype) and enable_categorical:
c:\Users\reyco\anaconda3\lib\site-packages\xgboost\data.py:345: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if is_categorical_dtype(dtype)
c:\Users\reyco\anaconda3\lib\site-packages\xgboost\data.py:336: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  return is_int or is_bool or is_float or is_categorical_dtype(dtype)

        Id  Real SalePrice  Predicted SalePrice
0     1461   169277.052498        119670.695312
1     1462   187758.393989        154496.921875
2     1463   183583.683570        175728.968750
3     1464   179317.477511        192542.984375
4     1465   150730.079977        202090.437500
...    ...             ...                  ...
1454  2915   167081.220949         80350.210938
1455  2916   164788.778231         86896.023438
1456  2917   219222.423400        153674.546875
1457  2918   184924.279659        123339.546875
1458  2919   187741.866657        226110.109375

[1459 rows x 3 columns]

In [18]:
test_data_encoded

,OverallQual,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,TotalBsmtSF,1stFlrSF,GrLivArea,FullBath,HalfBath,...,GarageCond_TA,PoolQC_Ex,PoolQC_Fa,PoolQC_Gd,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,5,1961,1961,0.0,468.0,882.0,896,896,1,0,...,True,False,0,True,False,False,False,False,True,False
1,6,1958,1958,108.0,923.0,1329.0,1329,1329,1,1,...,True,False,0,True,False,False,False,False,True,False
2,5,1997,1998,0.0,791.0,928.0,928,1629,2,1,...,True,False,0,True,False,False,False,False,True,False
3,6,1998,1998,20.0,602.0,926.0,926,1604,2,1,...,True,False,0,True,False,False,False,False,True,False
4,8,1992,1992,0.0,263.0,1280.0,1280,1280,2,0,...,True,False,0,True,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,4,1970,1970,0.0,0.0,546.0,546,1092,1,1,...,True,False,0,True,False,False,False,False,True,False
1455,4,1970,1970,0.0,252.0,546.0,546,1092,1,1,...,True,False,0,True,True,False,False,False,False,False
1456,5,1960,1996,0.0,1224.0,1224.0,1224,1224,1,0,...,True,False,0,True,True,False,False,False,False,False
1457,5,1992,1992,0.0,337.0,912.0,970,970,1,0,...,True,False,0,True,False,False,False,False,True,False
1458,7,1993,1994,94.0,758.0,996.0,996,2000,2,1,...,True,False,0,True,False,False,False,False,True,False

### Guardando las predicciones: Guardaste las predicciones en un archivo CSV.

In [31]:
# Cargar las predicciones que hiciste para el conjunto de prueba
test_predictions = xgb_model.predict(test_data_encoded)

# Crear un DataFrame con las ID y las predicciones
submission_df = pd.DataFrame({
    'Id': test_data['Id'],
    'SalePrice': test_predictions
})

# Guardar el DataFrame como un archivo CSV
submission_df.to_csv('submission.csv', index=False)

c:\Users\reyco\anaconda3\lib\site-packages\xgboost\data.py:312: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(dtype):
c:\Users\reyco\anaconda3\lib\site-packages\xgboost\data.py:314: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  elif is_categorical_dtype(dtype) and enable_categorical:
c:\Users\reyco\anaconda3\lib\site-packages\xgboost\data.py:345: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if is_categorical_dtype(dtype)
c:\Users\reyco\anaconda3\lib\site-packages\xgboost\data.py:336: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  return is_int or is_bool or is_float or is_categorical_dtype(dtype)

In [15]:
import joblib

# Guardar el modelo xgb_model en un archivo
joblib.dump(xgb_model, 'xgb_model.pkl')

['xgb_model.pkl']